name             'cyclescape'
maintainer       'Cyclestreets Ltd'
maintainer_email 'YOUR_EMAIL'
license          'MIT'
description      'Installs/Configures Cyclescape'
version          '0.5.2'

depends 'apt'
depends 'ssl'
depends 'apache2'
depends 'postgres'
depends 'ruby_build'
depends 'passenger_apache2'
depends 'exim4-light'
depends 'cyclescape-user'
depends 'cyclescape-backups'
depends 'ufw'
depends 'munin-plugins-rails'
depends 'java'
depends 'nodejs'
depends 'letsencrypt'
depends 'deploy_resource'
