name             'cyclescape'
maintainer       'Cyclestreets Ltd'
maintainer_email 'YOUR_EMAIL'
license          'MIT'
description      'Installs/Configures Cyclescape'
version          '0.1.0'

depends 'apt'
depends 'ssl'
depends 'apache2'
depends 'postgres'
depends 'ntp'
depends 'brightbox-ruby'
depends 'passenger_apache2'
depends 'postfix'
depends 'cyclescape-user'
depends 'cyclescape-backups'
depends 'ufw'
depends 'munin-plugins-rails'
depends 'java'
