name             'toolkit'
maintainer       'Cyclestreets Ltd'
maintainer_email 'YOUR_EMAIL'
license          'MIT'
description      'Installs/Configures toolkit'
version          '0.1.0'

depends 'ssl'
depends 'apache2'
depends 'postgres'
depends 'ntp'
depends 'ruby19'
depends 'passenger-gem'
depends 'postfix'
depends 'cyclekit-user'
depends 'toolkit-backups'
depends 'ufw'
depends 'munin-plugins-rails'